### ISSUE TITLE
[QUESTION] How to specify the output directory?

### ISSUE THREAD

**Issue by theLine** [SublimeLinter/SublimeLinter-javac#10]
How can I configure SublimeLinter to put the compiled `.class` files into a separate folder, e.g. `./bin`?

I know... it must be pretty easy, but I don't get it right :/

Here is my current config:

``` json
{
"user": {
    "linters": {
        "javac": {
            "@disable": false,
            "args": [
                "-d", "./bin/"
            ],
            "excludes": [],
            "lint": ""
        }
    }
}
```

**Comment by jawshooah** [comment]
Try `{project}/bin` instead.
