### ISSUE TITLE
Directory Not Found

### ISSUE THREAD

**Issue by Palidino** [SublimeLinter/SublimeLinter-javac#14]
I'm not really sure what's going on, I've been using this package for ages without any issues and haven't changed anything, but today I noticed that errors are no longer being displayed. After trying debug mode, I'm seeing the error "javac: directory not found: ${project}/../bin/" (my bin folder is located one directory higher than the sublime-project file). As I mentioned, up until today this has always worked just fine.

**Comment by braver** [comment]
Please try again with recent versions of SublimeLinter and this plugin.
