### ISSUE TITLE
Linter crashes with error message TypeError: unorderable types: int() < str()

### ISSUE THREAD

**Issue by SubhamSatyajeet** [SublimeLinter/SublimeLinter-javac#16]
Linter crashes on linting a Java file in which main method block's starting curly brace is absent. 
The error shown is 

`TypeError: unorderable types: int() < str()`

(Please see the attached image for details).

Windows 10, Version 1709
Sublime Text 3.0, (build 3143)
SublimeLinter 4.0.1

![linter-crashing](https://user-images.githubusercontent.com/7932787/37012789-66c472fe-211c-11e8-9e8f-9edfce8cfcc3.png)

**Comment by kaste** [comment]
A type error 👍 

Can you enable debug mode, open the console and show the actual output of running the cmd?

**Comment by kaste** [comment]
I have a PR against SublieLinter core here https://github.com/SublimeLinter/SublimeLinter/pull/1129

🤞

**Comment by SubhamSatyajeet** [comment]
Updated to SublimeLinter 4.2.0

The linter is not crashing anymore, and the expected error is being linted. Thank you so much!
Closing the issue now.
