### ISSUE TITLE
Destination breaking linter

### ISSUE THREAD

**Issue by Palidino** [SublimeLinter/SublimeLinter-javac#19]
```	
"SublimeLinter":
	{
		"linters":
		{
			"javac":
			{
				"args":
				[
					"-cp",
					"${project}/../data/lib/mysql.jar:${project}/../data/lib/xpp.jar:${project}/../data/lib/xstream.jar:${project}/../data/lib/filestore.jar:${project}/../data/lib/object-explorer.jar",
					"-sourcepath",
					"${project}/../src/",
					"-d",
					"${project}/../bin/"
				],
				"lint": "all"
			}
		}
	}
```

Removing the
`					"-d",
					"${project}/../bin/"`
Fixes the linter, re-adding it causes no errors to be shown. Turning on debugging also shows no information in the console, with the sublimelinter output showing "No lint results."

These settings used to work. Shortly after ${project} was re-added or fixed is when the linter stopped working, I just never got around to posting the issue.

Reverting to sublimelinter-javac 1.1.8 and sublimelinter 3.9.0 fixes the issue.

**Comment by kaste** [comment]
The way I look at something like this, is turn on debug mode. Look what `cmd` in which `cwd` (working dir) SublimeLinter here actually runs, and then I compare that to what *I* would run at the command line.

**Comment by Palidino** [comment]
Enabling debug doesn't provide any information at all. As long as I have
the -d flag set, the only debug I get is in the bottom left corner of
sublime saying "javac(ok)"

**Comment by Palidino** [comment]
Using $project works for the other flags and I forgot to mention that only
placing a -d flag in without even using $project, this issue still occurs
for me. For some reason, it seems that destination as a whole is breaking
the linter for me.

**Comment by kaste** [comment]
Seems like it can be closed.
