### ISSUE TITLE
Two Java classes inside two levels of folders cannot access each other according to linter

### ISSUE THREAD

**Issue by SubhamSatyajeet** [SublimeLinter/SublimeLinter-javac#20]
Setup:
Windows 10, Version 1803
Sublime Text 3.1.1, Build 3176
SublimeLinter 4.6.5
SublimeLinter-javac 1.1.11

Steps to reproduce the problem:
1) Create a folder (say ParentFolder).
2) Create a folder inside it (say ChildFolder).
3) Create two Java source code files inside it.
4) Invoke a static method of any class inside any method of the other class.

Problem:
The linter shows an error, saying that the class can't be found.
javac - cannot find symbol

Obviously, both files can compile with no errors in the command line.

Screenshot:
![image](https://user-images.githubusercontent.com/7932787/41756271-49f4014e-75f9-11e8-94c2-4b15defae590.png)

Additional Notes:
If I put them inside a folder and try it, it works as expected.
If I put them inside a folder _that is inside another folder_, then this problem arises.

**Comment by kaste** [comment]
You need to set some args here. Look for a good setting for `-classpath`, `-sourcepath`, and maybe `-d`. 

The way I usually approach something like this is to enable debug mode. And look what cmd in which cwd SublimeLinter executes here. Then I go to the CLI, execute the same cmd to see it failing. Then I slowly change the command for the better. 

In the end you can set such additional args in the SublimeLinter settings 

```
linters:
	javac:
		args: "..."
```

Note that you can point to subfolders using variables (look up the docs). E.g. `-sourcepath $folder/ChildFolder` etc.

**Comment by SubhamSatyajeet** [comment]
Oh. I see now that this is the way javac also behaves when it is executed via absolute paths. This is not a linter issue.

I'm closing this issue. Thanks for clearing that up! @kaste

**Comment by kaste** [comment]
Maybe, if you have something in your mind that could help people get started. We take PRs for the Readme as well. 😜
