### ISSUE TITLE
Report errors from multiple files in one go?

### ISSUE THREAD

**Issue by kaste** [SublimeLinter/SublimeLinter-javac#22]
https://github.com/SublimeLinter/SublimeLinter-javac/blob/23c50aea5026abbe8c6dfae57fc6bba09348b6cb/linter.py#L6

If we instead of "file" use the capturing group name "filename", SublimeLinter actually recognizes that and could read in errors from multiple files in one go.  T.i. 🤞 we could omit the `split_match` implementation here, maybe. 

@davidaurelio  Could you test that? You're already know how to hack on SL plugins and could probably easily test.

**Comment by davidaurelio** [comment]
@kaste with [these changes](https://github.com/davidaurelio/SublimeLinter-javac/commit/73fe5aa07dc27073c9efd500033bbf3fc0837b4b), the “Show All Errors” panel starts showing errors from files that I don’t have opened, grouped by files. Clicks on errors work. Is that what you meant?

**Comment by kaste** [comment]
Yeah, that's the feature. I don't know if it makes sense here. It is great for typecheckers, e.g. you change a function type/signature and it tells you all locations you broke/need to fix. 

Wdyt? Should we enable this feature?

**Comment by davidaurelio** [comment]
Sounds good to me. I will make a PR
