### ISSUE TITLE
javac not working in linux with java 1.7

### ISSUE THREAD

**Issue by isometric** [SublimeLinter/SublimeLinter-javac#3]
Running Ubuntu 12.04 LTS

$ whereis javac
javac: /usr/bin/javac /usr/bin/X11/javac /usr/share/man/man1/javac.1.gz

$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/lib/jvm/java-7-oracle/bin:/usr/lib/jvm/java-7-oracle/db/bin:/usr/lib/jvm/java-7-oracle/jre/bin

$ javac -version
javac 1.7.0_51

sense this does not make

**Comment by braver** [comment]
Sorry about letting this sit here for so long, but I can't imagine you're still waiting for help on this one.
