### ISSUE TITLE
javac runs pollute source directory with class files

### ISSUE THREAD

**Issue by automaticgiant** [SublimeLinter/SublimeLinter-javac#8]
It doesn't look like there is a flag to turn off output generation and only lint, so a temporary directory should be created to place generated files that can be cleaned up after running.

**Comment by AaronAsAChimp** [comment]
The best way I've found to make this work is the config trick I mentioned in Issue #9, but using the [-d option](http://www.codejava.net/java-core/tools/using-javac-command#DestDir). Then telling my version control to ignore that directory.

**Comment by kaste** [comment]
Closing bc -d is the correct way to go here imo.
