### ISSUE TITLE
Error: Package <pkg> does not exist; Gradle + JUnit project

### ISSUE THREAD

**Issue by sakovias** [SublimeLinter/SublimeLinter-javac#9]
I'm quite new to Java, so I apologize in advance if the problem is in my setup rather then the linter.

I use the Gradle build tool to run JUnit tests. The test dependecies are specified in my `build.gradle` file. The test file shows a bunch of "Package <pkg> does not exist" errors because it doesn't know where to get the dependencies from. The tests, however, have no problem running with `gradle build`.

Here's a screenshot:
![javac-junit-gradle](https://cloud.githubusercontent.com/assets/4750367/7218057/31d23a7a-e625-11e4-89bc-4432e89bf9a9.png)

To reproduce, please pull the code from https://github.com/exercism/xjava/tree/master/etl and take a look at `etl/src/test/java/EtlTest.java`.

Thanks!

**Comment by jawshooah** [comment]
Yeah, I'm not sure why this linter was created without a `classpath` option. I'd recommend using @reekoheek's [SublimeLinter-contrib-java](https://github.com/reekoheek/SublimeLinter-java) for now.

@skj3gg, what do you think about decommissioning this repo in favor of the above?

**Comment by AaronAsAChimp** [comment]
You can pass in additional arguments using the `args` option. It would nice if there were a better way of specifying it.

```js
{
	"SublimeLinter": {
		"linters": {
			"javac": {
				"args": [
					"-cp",
					"${project}/lib/*",
					"-sourcepath",
					"${project}/src/main/java/"
				]
			}
		}
	}
}
```

**Comment by rtmcached** [comment]
Solution by AaronAsAChimp works for me and should be in the readme settings section.

**Comment by 25A0** [comment]
@AaronAsAChimp's solution worked for me, too.
It's currently quite tricky to find this information, and I agree that this should be part of the readme -- so I [added a short explanation][1] to prevent that others spend as much time on this as I did.

#12 is a pull request for this. I'd be happy to hear feedback or suggestions for how to improve it.

[1]: https://github.com/25A0/SublimeLinter-javac/tree/javac-option-docs#passing-options-to-javac

**Comment by sakovias** [comment]
Looks like I forgot to close this issue. I'm currently using a `-cp` to add a library to class path *per project*. I think documentation improved a lot since I've last looked at it.

Great job guys!

---
Go to _Project_ > _Edit Project_ to add project-specific linter settings:

``` json
{
  "folders":
  [
    {
      "path": "/home/anton/calc/algorithms/homework"
    }
  ],
  "SublimeLinter":
  {
    "linters":
    {
      "javac": {
        "lint": "all",
        "args": [
          "-encoding", "UTF8",
          "-cp", "/usr/local/algs4/algs4.jar"
        ]
      }
    }
  }
}

```
